#pragma once

enum TokenType {
	T_ERROR = -1, T_EOF = 0,
	T_INC, T_DEC,
	T_ADD, T_SUBSTRACT, T_MULTIPLY, T_DIVIDE,
	T_ID, T_DIGITS, T_STRING,
	T_INT, T_DOUBLE, T_FLOAT, T_LONG, T_CHAR, T_SHORT,
	T_WHILE, T_IF, T_ELSE, T_DO,
	T_AUTO, T_BREAK, T_CASE,
	T_CONST, T_CONTINUE, T_DEFAULT,
	T_ENUM, T_EXTERN, T_FOR,
	T_GOTO, T_RETURN, T_REGISTER,
	T_SIGNED, T_SIZEOF, T_STATIC,
	T_STRUCT, T_SWITCH, T_TYPEDEF,
	T_UNION, T_UNSIGNED, T_VOID,
	T_SINGLE_COMMENT, T_L_MULTIPLE_COMMENT, T_R_MULTIPLE_COMMENT,
	T_L_PARENTHESIS, T_R_PARENTHESIS,
	T_L_SQUARE_BRACKET, T_R_SQUARE_BRACKET,
	T_L_BRACES, T_R_BRACES,
	T_SEMICOLON, T_COLON,
	T_COMPARE_LESS, T_COMPARE_MORE,
	T_EQUAL, T_NOT,
	T_SINGLE_QUOTE, T_DOUBLE_QUOTE,
	T_AND, T_OR,
	T_COMMA, T_POINT,
	T_SEPARATOR_TAB, T_SEPARATOR_SPACE, T_SEPARATOR_N, T_EOFS,
	T_VOLATILE, T_NOT_EQUAL

};